language: python

python:
  - "3.7"

services:
  - mysql

env:
  -DJANGO=2.2.3 DB=mysql

install:
  - pip install -r requirements.txt


before_script:
  - mysql -e 'create database test;' -u root

script:
  - coverage run --source='.' --omit=*/migrations/* fms_api/manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
