# Generated by Django 2.2.5 on 2019-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_trans',
            field=models.CharField(choices=[(2, 'Contribution'), (1, 'Write-off')], default='', max_length=20, verbose_name='Transaction type'),
            preserve_default=False,
        ),
    ]
