# Generated by Django 2.2.5 on 2019-09-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_trans',
            field=models.CharField(choices=[('Contribution', 'Contribution'), ('Write-off', 'Write-off')], max_length=20, verbose_name='Transaction type'),
        ),
    ]
